spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ctdz?characterEncoding=utf8&useSSL=false
    username: root
    password: "root"

# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml

server:
  port: 8080